# Generated by Django 2.2.7 on 2019-12-03 18:25

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=builtins.id, max_length=100),
            preserve_default=False,
        ),
    ]
